# 01: Examining the Emojibase Dataset
I know the emojibase dataset is a collection of dictionaries with emoji and tags, but I want to look at what words I have.

In [1]:
from emoji import assets
import json

with open(assets.get_emojibase(), "r", encoding="utf-8") as file:
    data = json.load(file)

len(data)

1949

In [4]:
import pandas as pd

emoji_df = pd.DataFrame.from_dict(data)[['label', 'emoji', 'tags']].dropna()
emoji_df

,label,emoji,tags
26,grinning face,😀,"[cheerful, cheery, face, grin, grinning, happy..."
27,grinning face with big eyes,😃,"[awesome, big, eyes, face, grin, grinning, hap..."
28,grinning face with smiling eyes,😄,"[eye, eyes, face, grin, grinning, happy, laugh..."
29,beaming face with smiling eyes,😁,"[beaming, eye, eyes, face, grin, grinning, hap..."
30,grinning squinting face,😆,"[closed, eyes, face, grinning, haha, hahaha, h..."
...,...,...,...
1944,flag: Zambia,🇿🇲,"[ZM, flag]"
1945,flag: Zimbabwe,🇿🇼,"[ZW, flag]"
1946,flag: England,🏴󠁧󠁢󠁥󠁮󠁧󠁿,"[flag, gbeng]"
1947,flag: Scotland,🏴󠁧󠁢󠁳󠁣󠁴󠁿,"[flag, gbsct]"
1948,flag: Wales,🏴󠁧󠁢󠁷󠁬󠁳󠁿,"[flag, gbwls]"

In [42]:
wordset = set()
wordcounts = dict()
wordemoji = dict()

for emoji, taglist in emoji_df[['emoji', 'tags']].itertuples(index=False, name=None):
    for tag in taglist:
        wordset.add(tag)
        wordcounts[tag] = wordcounts.get(tag, 0) + 1
        emojilist = wordemoji.get(tag, [])
        wordemoji[tag] = emojilist + [emoji]

word_df = pd.DataFrame.from_dict(wordcounts, orient='index').sort_values(by=0, ascending=False)
word_df = word_df.assign(wordemoji=wordemoji)
word_df

          0                                          wordemoji
flag    274  [⛳️, 📫️, 📪️, 📬️, 📭️, 🏁, 🚩, 🏴, 🏳️, 🏳️‍🌈, 🏳️‍⚧️,...
face    162  [😀, 😃, 😄, 😁, 😆, 😅, 🤣, 😂, 🙂, 🙃, 🫠, 😉, 😊, 😇, 🥰, ...
animal  122  [😺, 😸, 😹, 😻, 😼, 😽, 🙀, 😿, 😾, 🙉, 🙊, 🐵, 🐒, 🦍, 🦧, ...
man     113  [🧔‍♂️, 👨‍🦰, 👨‍🦱, 👨‍🦳, 👨‍🦲, 👱‍♂️, 👴, 🙍‍♂️, 🙎‍♂️...
woman   108  [🧔‍♀️, 👩‍🦰, 👩‍🦱, 👩‍🦳, 👩‍🦲, 👱‍♀️, 👵, 🙍‍♀️, 🙎‍♀️...
...     ...                                                ...
SJ        1                                               [🇸🇯]
SK        1                                               [🇸🇰]
SL        1                                               [🇸🇱]
SM        1                                               [🇸🇲]
SN        1                                               [🇸🇳]

[3638 rows x 2 columns]